### PR TITLE
Docs: gif and unit test

### PR DESCRIPTION
**Pull request by meniRoy**
- added a demo gif to the readme 
- added unit test section to the readme

### CODE REVIEW

**Comment by meniRoy** [comment]
[Docs: unit test section and gif](https://trello.com/c/LbEnA59X/10805-docs-unit-test-section-and-gif)

**Review by weinguy-env0 — COMMENTED** [review]
I would add one more gif of switching branches and seeing it loads the relevant environments

**Comment by meniRoy** [comment]
> I would add one more gif of switching branches and seeing it loads the relevant environments 

@liranfarage89 should we add this now or after the relese?

**Comment by meniRoy** [comment]
> I would add one more gif of switching branches and seeing it loads the relevant environments

4e0826df3ea728f0c517c37fed13c358b7a5c338

**Review by weinguy-env0 — APPROVED** [review]

**Pull request merged**
